# Generated by Django 2.1.1 on 2018-09-30 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название маячка')),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID маячка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Маячок',
                'verbose_name_plural': 'Маячки',
                'ordering': ('title',),
            },
        ),
    ]
